# BrAPI
#
# Run with "docker compose up"
# Stop with "docker compose down"
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# Database name: drupal
# Database username: postgres
# Database password: pgBr4P!_D0cker
# fpm port: 9000

version: '3.4'

services:

  brapi:
    # image: guignon:brapi4.0.0beta3-drupal10.1.2-php8.2-fpm-bookworm
    image: brapi
    env_file:
      - 'brapi.env'
    volumes:
      - drupal-volume:/opt/drupal
      - ./drupal/modules:/opt/drupal/web/modules
      - ./drupal/profiles:/opt/drupal/web/profiles
      - ./drupal/themes:/opt/drupal/web/themes
      - ./drupal/vendor:/opt/drupal/vendor
      - ./drupal/config:/opt/drupal/config
      - ./drupal/private:/opt/drupal/private
      - ./drupal/sites/default:/opt/drupal/web/sites/default
      - ./php:/opt/drupal/php
    depends_on:
      - db
    restart: always

  proxy:
    image: nginx
    ports:
      - 8080:80
      - 8642:8642
    env_file:
      - 'brapi.env'
    volumes:
      - type: bind
        source: ./proxy/brapi-fpm.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - drupal-volume:/opt/drupal
    depends_on:
      - brapi
    restart: always

  db:
    image: postgres:15
    env_file:
      - 'brapi.env'
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  drupal-volume:
